spring:
  config:
    import:
      - classpath:security/common/application.yaml
      - classpath:security/community-app-external-api/application.yaml
      - classpath:security/mariadb/application.yaml