spring:
  config:
    import:
      - classpath:security/common/application.yaml
      - classpath:security/air-quality-app-external-api/application.yaml
      - classpath:security/mariadb/application.yaml
      - classpath:security/module-security/application.yaml
      - classpath:security/module-core/application.yaml