
# 정훈
spring:

  config:
    activate:
      on-profile: kjh
  datasource:
    url: jdbc:mariadb://localhost:3306/hat_local_community
    username: root
    password: 12341234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true



---