spring:
  config:
    import:
      - classpath:security/common/application.yaml
      - classpath:security/air-quality-app-batch/application.yaml
      - classpath:security/mariadb/application.yaml
      - classpath:security/module-core/application.yaml